apiVersion: apps/v1
kind: Deployment
metadata:
  name: jicofo
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jicofo
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jicofo
    spec:
      containers:
      - env:
        - name: XMPP_SERVER
          value: prosody
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: JICOFO_COMPONENT_SECRET
          value: {{ .Values.jicofo.componentSecret | quote }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.authUser }}
        - name: JICOFO_AUTH_PASSWORD
          value: {{ .Values.jicofo.authPassword | quote }}
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: JIGASI_BREWERY_MUC
          value: {{ .Values.jigasi.breweryMuc }}
        - name: JIGASI_SIP_URI
          value: {{ .Values.jigasi.sipUri }}
        - name: JIBRI_BREWERY_MUC
          value: jibribrewery
        - name: JIBRI_PENDING_TIMEOUT
          value: {{ .Values.jibri.pendingTimeout | quote}}
        - name: TZ
          value: {{ .Values.timezone }}
        image: jitsi/jicofo
        name: jicofo
        resources: {}
      restartPolicy: Always
status: {}
