{{- if (.Values.jigasi.enabled) }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: jigasiingress
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      jigasi:
        paths:
          - path: /
            backend:
              serviceName: jigasi
              # Need more ports? Append with this command:
              # for i in {20000..20050}; do echo "              servicePort: jigasi-$i"; done  >> jigasi-ingress.yaml        
              servicePort: jigasi-20000
              servicePort: jigasi-20001
              servicePort: jigasi-20002
              servicePort: jigasi-20003
              servicePort: jigasi-20004
              servicePort: jigasi-20005
              servicePort: jigasi-20006
              servicePort: jigasi-20007
              servicePort: jigasi-20008
              servicePort: jigasi-20009
              servicePort: jigasi-20010
              servicePort: jigasi-20011
              servicePort: jigasi-20012
              servicePort: jigasi-20013
              servicePort: jigasi-20014
              servicePort: jigasi-20015
              servicePort: jigasi-20016
              servicePort: jigasi-20017
              servicePort: jigasi-20018
              servicePort: jigasi-20019
              servicePort: jigasi-20020
              servicePort: jigasi-20021
              servicePort: jigasi-20022
              servicePort: jigasi-20023
              servicePort: jigasi-20024
              servicePort: jigasi-20025
              servicePort: jigasi-20026
              servicePort: jigasi-20027
              servicePort: jigasi-20028
              servicePort: jigasi-20029
              servicePort: jigasi-20030
              servicePort: jigasi-20031
              servicePort: jigasi-20032
              servicePort: jigasi-20033
              servicePort: jigasi-20034
              servicePort: jigasi-20035
              servicePort: jigasi-20036
              servicePort: jigasi-20037
              servicePort: jigasi-20038
              servicePort: jigasi-20039
              servicePort: jigasi-20040
              servicePort: jigasi-20041
              servicePort: jigasi-20042
              servicePort: jigasi-20043
              servicePort: jigasi-20044
              servicePort: jigasi-20045
              servicePort: jigasi-20046
              servicePort: jigasi-20047
              servicePort: jigasi-20048
              servicePort: jigasi-20049
              servicePort: jigasi-20050
{{- end }}