apiVersion: v1
kind: Service
metadata:
  labels:
    app: jitsi
  name: jvb
spec:
  type: NodePort
  ports:
  - name: udp
    port: {{ .Values.jvb.containerPortUDP }}
    nodePort: {{ .Values.jvb.containerPortUDP }}
    protocol: UDP
    targetPort: {{ .Values.jvb.containerPortUDP }}
  - name: tcp
    port: {{ .Values.jvb.containerPortTCP }}
    nodePort: {{ .Values.jvb.containerPortTCP }}
    protocol: TCP
    targetPort: {{ .Values.jvb.containerPortTCP }}
  selector:
    service: jvb
