apiVersion: apps/v1
kind: Deployment
metadata:
  name: jvb
spec:
  replicas: 1
  selector:
    matchLabels:
      service: jvb
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: jvb
    spec:
      containers:
      - env:
        - name: XMPP_SERVER
          value: prosody
        - name: DOCKER_HOST_ADDRESS
          value: {{ .Values.dockerHostAddress }}
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: JVB_PORT
          value: "30000"
        - name: JVB_TCP_PORT
          value: "30001"
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.authUser }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.authPassword }}
        - name: JVB_BREWERY_MUC
          value: jvbbrewery
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: JVB_STUN_SERVERS
          value: ""
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.authUser }}
        - name: TZ
          value: {{ .Values.timezone }}
        image: jitsi/jvb
        name: jvb
        ports:
        - containerPort: {{ .Values.jvb.containerPortUDP }}
          protocol: UDP
        - containerPort: {{ .Values.jvb.containerPortTCP }}
        resources: {}
      restartPolicy: Always
status: {}
