apiVersion: apps/v1
kind: Deployment
metadata:
  name: prosody
spec:
  replicas: 1
  selector:
    matchLabels:
      service: prosody
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: prosody
    spec:
      containers:
      - env:
        {{- if (.Values.auth.enabled) }}
        - name: AUTH_TYPE
          value: {{ .Values.auth.authtype }}
        - name: ENABLE_AUTH
          value: "1"
        {{- if (.Values.auth.enableGuests) }}
        - name: ENABLE_GUESTS
          value: "1"
        {{- end }}
        {{- if (eq .Values.auth.authtype "ldap") }}
        - name: LDAP_URL
          value: {{ .Values.auth.ldap.url }}
        - name: LDAP_BASE
          value: {{ .Values.auth.ldap.base }}
        - name: LDAP_BINDDN
          value: {{ .Values.auth.ldap.binddn }}
        - name: LDAP_BINDPW
          value: {{ .Values.auth.ldap.bindpw }}
        - name: LDAP_FILTER
          value: {{ .Values.auth.ldap.filter }}
        - name: LDAP_AUTH_METHOD
          value: {{ .Values.auth.ldap.authMethod }}
        - name: LDAP_VERSION
          value: {{ .Values.auth.ldap.version | quote }}
        {{- if (.Values.auth.ldap.useTLS) }}
        - name: LDAP_USE_TLS
          value: "1"
        - name: LDAP_TLS_CIPHERS
          value: {{ .Values.auth.ldap.TLSCiphers }}
        {{- if (.Values.auth.TLScheckPeer) }}
        - name: LDAP_TLS_CHECK_PEER
          value: 1
        - name: LDAP_TLS_CACERT_FILE
          value: {{ .Values.auth.ldap.TLSCaCertFile }}
        - name: LDAP_TLS_CACERT_DIR
          value: {{ .Values.auth.ldap.TLSCaCertDir }}
        {{- end }}
        {{- if (.Values.auth.ldap.startTLS) }}
        - name: LDAP_START_TLS
          value: "1"
        {{- end }}
        {{- end }}
        {{- end }}
        {{- if (eq .Values.auth.authtype "jwt") }}
        - name: JWT_APP_ID
          value: {{ .Values.auth.jwt.appID }}
        - name: JWT_APP_SECRET
          value: {{ .Values.auth.jwt.appSecret }}
        - name: JWT_ACCEPTED_ISSUERS
          value: {{ .Values.auth.jwt.acceptedIssuers }}
        - name: JWT_ACCEPTED_AUDIENCES
          value: {{ .Values.auth.jwt.acceptedAudiences }}
        - name: JWT_ASAP_KEYSERVER
          value: {{ .Values.auth.jwt.asapKeyserver }}
        {{- if (.Values.auth.jwt.allowEmpty) }}
        - name: JWT_ALLOW_EMPTY
          value: "1"
        {{- end }}
        - name: JWT_AUTH_TYPE
          value: {{ .Values.auth.jwt.authType }}
        - name: JWT_TOKEN_AUTH_MODULE
          value: {{ .Values.auth.jwt.tokenAuthModule }}
        {{- end }}
        {{- end }}
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: JICOFO_COMPONENT_SECRET
          value: {{ .Values.jicofo.componentSecret }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.authUser }}
        - name: JICOFO_AUTH_PASSWORD
          value: {{ .Values.jicofo.authPassword }}
        - name: JVB_COMPONENT_SECRET
          value: {{ .Values.jvb.componentSecret }}
        - name: JVB_AUTH_USER
          value: {{ .Values.jvb.authUser }}
        - name: JVB_AUTH_PASSWORD
          value: {{ .Values.jvb.authPassword }}
        - name: XMPP_INTERNAL_MUC_DOMAIN
          value: internal-muc.meet.jitsi
        - name: TZ
          value: {{ .Values.timezone }}
        image: jitsi/prosody
        name: prosody
        ports:
        - containerPort: 5222
        - containerPort: 5280
        - containerPort: 5347
        resources: {}
      restartPolicy: Always
status: {}
