apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - env:
#        - name: ENABLE_HTTP_REDIRECT
#          value: "1"
        {{- if (.Values.letsecrypt.enabled) }}
        - name: ENABLE_LETSENCRYPT
          value: "1"
        - name: LETSENCRYPT_DOMAIN
          value: {{ .Values.ingress.host }}
        - name: LETSENCRYPT_EMAIL
          value: {{ .Values.letsencrypt.email }}
        {{- end }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.authUser }}
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_BOSH_URL_BASE
          value: http://prosody:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: TZ
          value: Europe/Paris
        image: jitsi/web
        name: web
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
status: {}
