apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 1
  selector:
    matchLabels:
      service: web
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        service: web
    spec:
      containers:
      - env:
#        - name: ENABLE_HTTP_REDIRECT
#          value: "1"
        {{- if (.Values.auth.enabled) }}
        - name: ENABLE_AUTH
          value: "1"
        {{- if (.Values.auth.enableGuests) }}
        - name: ENABLE_GUESTS
          value: "1"
        {{- end }}
        {{- end }}
        {{- if (.Values.letsencrypt.enabled) }}
        - name: ENABLE_LETSENCRYPT
          value: "1"
        - name: LETSENCRYPT_DOMAIN
          value: {{ .Values.ingress.host }}
        - name: LETSENCRYPT_EMAIL
          value: {{ .Values.letsencrypt.email }}
        {{- end }}
        - name: JICOFO_AUTH_USER
          value: {{ .Values.jicofo.authUser | quote }}
        - name: XMPP_DOMAIN
          value: meet.jitsi
        - name: XMPP_AUTH_DOMAIN
          value: auth.meet.jitsi
        - name: XMPP_BOSH_URL_BASE
          value: http://prosody:5280
        - name: XMPP_MUC_DOMAIN
          value: muc.meet.jitsi
        - name: TZ
          value: {{ .Values.timezone }}
        {{- if (.Values.jibri.enableRecording) }}
        - name: ENABLE_RECORDING
          value: "1"
        - name: JIBRI_BREWERY_MUC
          value: jibribrewery
        - name: JIBRI_PENDING_TIMEOUT
          value: {{ .Values.jibri.pendingTimeout | quote}}
        - name: JIBRI_XMPP_USER
          value: {{ .Values.jibri.xmppUser }}
        - name: JIBRI_XMPP_PASSWORD
          value: {{ .Values.jibri.xmppPassword }}
        - name: JIBRI_RECORDER_USER
          value: {{ .Values.jibri.recorderUser }}
        - name: JIBRI_RECORDER_PASSWORD
          value: {{ .Values.jibri.recorderPassword | quote }}
        {{- end }}
        image: jitsi/web
        name: web
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
status: {}
